CREATE TABLE  `lastwm`.`orders` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`DATETIME` DATETIME NOT NULL ,
`LASTFMUSER` VARCHAR( 15 ) NOT NULL ,
`MONTHS` INT( 2 ) NOT NULL ,
`PAID` INT( 1 ) NOT NULL ,
`STATUS` INT( 1 ) NOT NULL
) ENGINE = MYISAM ;
